# Write your code here :-)
from tkinter import*
obj=Tk()
obj.geometry("544x500")
obj.title("Calculator")
obj.configure(bg="grey")
# this svalue is related to entry obj get retrieves valye,set would set value
svalue=StringVar()
svalue.set("")
def click(event):
    global svalue
# would get button value
    text=event.widget.cget("text")
    if text=="=":
        c=(svalue.get())
    # eval function would take string and eval it as a python function
        value=eval(c)
        svalue.set(value)
        obj.update()
    elif text=="C":
        svalue.set('')
        obj.update()

    else:
        svalue.set(svalue.get()+str(text))
        obj.update()
e=Entry(obj,text=svalue,font=("arial",25,"bold"),relief="sunken")
e.pack(padx=80,pady=50,ipady=15)
f=Frame(obj,borderwidth=6,bg="white")
f.pack(fill="x")
b=Button(f,text=9,font=("arial",15,"bold"),padx=15,pady=15)
b.bind("<Button-1>",click)
b.pack(side="left",padx=15,pady=15)
b1=Button(f,text=8,font=("arial",15,"bold"),padx=15,pady=15)
b1.bind("<Button-1>",click)
b1.pack(side="left",padx=15,pady=15)
b2=Button(f,text=7,font=("arial",15,"bold"),padx=15,pady=15)
b2.bind("<Button-1>",click)
b2.pack(side="left",padx=15,pady=15)
b3=Button(f,text=6,font=("arial",15,"bold"),padx=15,pady=15)
b3.bind("<Button-1>",click)
b3.pack(side="left",padx=15,pady=15)
b4=Button(f,text="5",font=("arial",15,"bold"),padx=15,pady=15)
b4.bind("<Button-1>",click)
b4.pack(side="left",padx=15,pady=15)
b5=Button(f,text='4',font=("arial",15,"bold"),padx=15,pady=15)
b5.bind("<Button-1>",click)
b5.pack(side="left",padx=15,pady=15)



f1=Frame(obj,borderwidth=6,bg="white")
f1.pack(fill="x")
b=Button(f1,text=3,font=("arial",15,"bold"),padx=15,pady=15)
b.bind("<Button-1>",click)
b.pack(side="left",padx=15,pady=15)
b1=Button(f1,text=2,font=("arial",15,"bold"),padx=15,pady=15)
b1.bind("<Button-1>",click)
b1.pack(side="left",padx=15,pady=15)
b2=Button(f1,text=1,font=("arial",15,"bold"),padx=15,pady=15)
b2.bind("<Button-1>",click)
b2.pack(side="left",padx=15,pady=15)
b3=Button(f1,text=0,font=("arial",15,"bold"),padx=15,pady=15)
b3.bind("<Button-1>",click)
b3.pack(side="left",padx=15,pady=15)
b4=Button(f1,text="=",font=("arial",15,"bold"),padx=15,pady=15)
b4.bind("<Button-1>",click)
b4.pack(side="left",padx=15,pady=15)
b5=Button(f1,text='+',font=("arial",15,"bold"),padx=15,pady=15)
b5.bind("<Button-1>",click)
b5.pack(side="left",padx=15,pady=15)



f2=Frame(obj,borderwidth=6,bg="white")
f2.pack(fill="x")
b=Button(f2,text='-',font=("arial",15,"bold"),padx=15,pady=15)
b.bind("<Button-1>",click)
b.pack(side="left",padx=15,pady=15)
b1=Button(f2,text='*',font=("arial",15,"bold"),padx=15,pady=15)
b1.bind("<Button-1>",click)
b1.pack(side="left",padx=15,pady=15)
b2=Button(f2,text='/',font=("arial",15,"bold"),padx=15,pady=15)
b2.bind("<Button-1>",click)
b2.pack(side="left",padx=15,pady=15)
b3=Button(f2,text='%',font=("arial",15,"bold"),padx=15,pady=15)
b3.bind("<Button-1>",click)
b3.pack(side="left",padx=15,pady=15)
b4=Button(f2,text="C",font=("arial",15,"bold"),padx=15,pady=15)
b4.bind("<Button-1>",click)
b4.pack(side="left",padx=15,pady=15)
b5=Button(f2,text='**',font=("arial",15,"bold"),padx=15,pady=15)
b5.bind("<Button-1>",click)
b5.pack(side="left",padx=15,pady=15)

obj.mainloop()
